name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 16 * * *"}]
  # Run workflow manually
  workflow_dispatch:
  # Run workflow when pushing on main
  push: {branches: ["main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Lizosy
          base: header, activity, community, repositories, metadata
          filename: metrics-main.svg
          template: classic
          base_indepth: yes
          base_hireable: yes

  metrics-plugin-activity:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Lizosy
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 0
          plugin_activity_filter: push, issue, pr, release, fork, review, ref/create, star, public
          base: ""
          filename: metrics-plugin-activity.svg
          template: classic
          repositories: 240
          repositories_batch: 40

  metrics-plugin-isocalendar:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Lizosy
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          base: ""
          filename: metrics-plugin-isocalendar.svg
          template: classic

  leetcode-metrics:
    runs-on: ubuntu-latest
    environment:
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: NOT_NEEDED
          user: lizosy
          plugin_leetcode: yes
          plugin_leetcode_sections: solved, skills, recent
          base: ""
          filename: metrics-plugin-leetcode.svg
          template: classic
